MTK_CPU = arm_cortexa7

TARGET_ARCH_VARIANT = armv7-a-neon

MODEM_UMTS_TDD128_MODE = no

MTK_ENGINEERMODE_INTERNAL_APP = yes

MTK_FIRST_MD = 1
MTK_FOTA_ENTRY = no
MTK_FLIGHT_MODE_POWER_OFF_MD = yes

MTK_SCOMO_ENTRY = no
MTK_SEC_SECRO_AC_SUPPORT=yes

MTK_OGM_PLAYBACK_SUPPORT = no

MTK_MTKPS_PLAYBACK_SUPPORT = no
MTK_CHKIMGSIZE_SUPPORT = no
MTK_MMPROFILE_SUPPORT=yes

MTK_DP_FRAMEWORK = yes
MTK_ION_SUPPORT = yes

MTK_ENABLE_MD1 = no
MTK_ENABLE_MD2 = no

MTK_FD_SUPPORT=yes
MTK_FD_FORCE_REL_SUPPORT=yes

CUSTOM_KERNEL_SSW=generic

MTK_SWIP_VORBIS=yes

MULTI_CH_PLAYBACK_SUPPORT=no

MTK_MERGE_INTERFACE_SUPPORT=yes

MTK_PRODUCT_INFO_SUPPORT=yes

HAVE_MTKLOUDNESS_EFFECT=yes
MTK_VSS_SUPPORT = no 

NATIVE_AUDIO_PREPROCESS_ENABLE=yes
